omitted extra vscode stuff

diff --git a/scripts/install-desktop-exts b/scripts/install-desktop-exts
--- a/scripts/install-desktop-exts
+++ b/scripts/install-desktop-exts
@@ -53,56 +53,15 @@ fi
 if [ "x${MODE}" = "xvscode" ]
 then
     # Install extensions for code.
-    msg "Install VSCode extensions."
-    CODE_EXTENSIONS="hookyqr.beautify
-        esbenp.prettier-vscode
-        ms-vscode.cpptools-extension-pack
-        formulahendry.code-runner
-        streetsidesoftware.code-spell-checker
-        krvajalm.linter-gfortran
-        bat67.matlab-extension-pack
-        rebornix.ruby
-        ikuyadeu.r
-        swellaby.rust-pack
-        ms-azuretools.vscode-docker
-        grapecity.gc-excelviewer
-        jaydenlin.google-complete-me
-        ecmel.vscode-html-css
-        syler.sass-indented
-        jock.svg
-        dbaeumer.vscode-eslint
-        wholroyd.jinja
-        silvenon.mdx
-        james-yu.latex-workshop
-        tomoki1207.pdf
-        davidanson.vscode-markdownlint
-        shd101wyy.markdown-preview-enhanced
-        kiteco.kite
-        ms-python.python
-        ms-python.vscode-pylance
-        kevinrose.vsc-python-indent
-        ms-toolsai.jupyter
-        magicstack.magicpython
-        mechatroner.rainbow-csv
-        zainchen.json
-        bungcip.better-toml
-        redhat.vscode-yaml
-        shakram02.bash-beautify
-        ms-vscode.powershell
-        vscode-icons-team.vscode-icons
-        pkief.material-icon-theme
-        pkief.material-product-icons
-        github.github-vscode-theme
-        dracula-theme.theme-dracula
-        eamodio.gitlens
-        mhutchie.git-graph"
+    msg "omitted - Install VSCode extensions."
     for c_ext in ${CODE_EXTENSIONS}; do
-        code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
+        msg "omitted - Install VSCode extensions. c_ext "
+      #  code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
     done
 
     if [ "x${WITH_CHINESE}" = "xtrue" ]
     then
-        code --install-extension ms-ceintl.vscode-language-pack-zh-hans --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
+    #    code --install-extension ms-ceintl.vscode-language-pack-zh-hans --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
     fi
 fi
 
@@ -110,31 +69,31 @@ fi
 if [ "x${MODE}" = "xvscodelocal" ]
 then
     # Install extensions for code by local installation packs.
-    msg "Install VSCode extensions by local installation packs."
-    mkdir -p /root/vscodepacks || fail
-    wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/snapshot-vscode-ext-041822.tar.xz | tar xJ -C "/root/vscodepacks/" || fail
+    msg "omitted - Install VSCode extensions by local installation packs."
+    # mkdir -p /root/vscodepacks || fail
+    # wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/snapshot-vscode-ext-041822.tar.xz | tar xJ -C "/root/vscodepacks/" || fail
 
     for c_ext in "/root/vscodepacks"/*.vsix ; do
-        msg "Install VSCode ext (local): ${c_ext}."
-        code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
+        msg "omitted - Install VSCode ext (local): ${c_ext}."
+     #    code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
     done
 
     if [ "x${WITH_CHINESE}" = "xtrue" ]
     then
         for c_ext in "/root/vscodepacks/zh_cn"/*.vsix ; do
-            msg "Install VSCode ext (local): ${c_ext}."
-            code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
+            msg "omitted - Install VSCode ext (local): ${c_ext}."
+            # code --install-extension ${c_ext} --extensions-dir "${USER_ROOT}/.vscode/extensions" --user-data-dir "${USER_ROOT}/.vscode/settings" || fail
         done
     fi
 
-    rm -rf /root/vscodepacks || fail
+    # rm -rf /root/vscodepacks || fail
 fi
 
 
 if [ "x${MODE}" = "xrust" ]
 then
     # Install Rust and Cargo to a global location.
-    msg "Install Rust and Cargo."
+    msg "Install Rust and Cargo new."
     apt-get update -qq || fail
     apt-get install -y libffi-dev libssl-dev || fail
     RUSTUP_HOME=/apps/rust
@@ -149,49 +108,37 @@ then
         wget -O- https://sh.rustup.rs | sh -s -- -y --no-modify-path || fail
     fi
     source ${CARGO_HOME}/env || fail
-    rustup toolchain install 1.60.0 || fail
-    rustup default 1.60.0 || fail
+    rustup toolchain install stable || fail
+    rustup default stable || fail
     cargo install cargo-c || fail
 fi
 
 
-if [ "x${MODE}" = "xfbrowser" ]
-then
-    # Install FileBrowser.
-    msg "Install FileBrowser."
-    mkdir -p /usr/local/bin || fail
-    mkdir -p ${USER_ROOT}/filebrowser || fail
-    if [ "x${USE_CURL}" == "x1" ]
-    then
-        curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash || fail
-    else
-        wget -O- https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash || fail
-    fi
-fi
+
 
 
 if [ "x${MODE}" = "xomp" ]
 then
     # Install Oh-my-posh.
-    msg "Install Oh-my-posh."
+    msg "omitted -  installing Oh-my-posh."
     # Get fonts.
-    wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/share-fonts-omp-v2.1.0.tar.xz | tar xJ -C "/usr/share/fonts/" || fail
+    # wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/share-fonts-omp-v2.1.0.tar.xz | tar xJ -C "/usr/share/fonts/" || fail
     # Get OMP.
-    wget -O- https://gist.githubusercontent.com/cainmagi/99a8dbfe175fccdc8b3457d14c67e2b8/raw/install-omp.sh | bash -s -- --skip-basic --skip-fonts user=${USER_NAME} || fail
+    # wget -O- https://gist.githubusercontent.com/cainmagi/99a8dbfe175fccdc8b3457d14c67e2b8/raw/install-omp.sh | bash -s -- --skip-basic --skip-fonts user=${USER_NAME} || fail
     # Get extra theme.
-    mkdir -p "${USER_ROOT}/.poshthemes" || fail
-    wget -O "${USER_ROOT}/.poshthemes/paradox-alt.omp.json" https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/paradox-alt.omp.json || fail
-    ln -s "${USER_ROOT}/.poshthemes" "/root/.poshthemes" || fail
+    # mkdir -p "${USER_ROOT}/.poshthemes" || fail
+    # wget -O "${USER_ROOT}/.poshthemes/paradox-alt.omp.json" https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/paradox-alt.omp.json || fail
+    # ln -s "${USER_ROOT}/.poshthemes" "/root/.poshthemes" || fail
     # Get terminal configs.
-    wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/home-omp-configs.tar.xz | tar xJ -C "${USER_ROOT}/" || fail
+    # wget -O- https://github.com/cainmagi/Dockerfiles/releases/download/xubuntu-v1.7-u20.04/home-omp-configs.tar.xz | tar xJ -C "${USER_ROOT}/" || fail
 fi
 
 
 if [ "x${MODE}" = "xscripts" ]
 then
     # Get optional scripts.
-    msg "Put optional scripts in \"${USER_ROOT}\"."
-    wget -O "${USER_ROOT}/install-omp.sh" https://gist.githubusercontent.com/cainmagi/99a8dbfe175fccdc8b3457d14c67e2b8/raw/install-omp.sh || fail
-    wget -O "${USER_ROOT}/install-gcc.sh" https://gist.githubusercontent.com/cainmagi/eaa93dd3c88672cc76e565a2081399d0/raw/install-gcc.sh || fail
-    wget -O "${USER_ROOT}/install-ffmpeg-5-0.sh" https://raw.githubusercontent.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/deps-3.2.0/install-ffmpeg-5_0.sh || fail
+    msg "omitted - puttting optional scripts in \"${USER_ROOT}\"."
+    # wget -O "${USER_ROOT}/install-omp.sh" https://gist.githubusercontent.com/cainmagi/99a8dbfe175fccdc8b3457d14c67e2b8/raw/install-omp.sh || fail
+    # wget -O "${USER_ROOT}/install-gcc.sh" https://gist.githubusercontent.com/cainmagi/eaa93dd3c88672cc76e565a2081399d0/raw/install-gcc.sh || fail
+    # wget -O "${USER_ROOT}/install-ffmpeg-5-0.sh" https://raw.githubusercontent.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/deps-3.2.0/install-ffmpeg-5_0.sh || fail
 fi
